<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StokTakip.DataAccess\StokTakip.DataAccess.csproj" />
    <ProjectReference Include="..\StokTakip.Entities\StokTakip.Entities.csproj" />
  </ItemGroup>

</Project>
