SET client_encoding = 'UTF8';

-- ============================================================
-- StokTakipSistemi PostgreSQL veritabani kurulum dosyasi
-- Bu dosya tablolari, iliskileri, kontrolleri ve ornek verileri olusturur.
-- ============================================================

-- Once iliskili alt tablolar silinir, sonra ana tablolar silinir.
DROP TABLE IF EXISTS ai_sorgu_gecmisi;
DROP TABLE IF EXISTS raporlar;
DROP TABLE IF EXISTS kritik_stoklar;
DROP TABLE IF EXISTS stok_cikislar;
DROP TABLE IF EXISTS stok_girisler;
DROP TABLE IF EXISTS urunler;
DROP TABLE IF EXISTS saklama_kosullari;
DROP TABLE IF EXISTS kategoriler;
DROP TABLE IF EXISTS kullanicilar;

-- ============================================================
-- Ana tablolar: kullanicilar, kategoriler ve saklama kosullari
-- ============================================================

CREATE TABLE kullanicilar (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad_soyad VARCHAR(100) NOT NULL,
    kullanici_adi VARCHAR(50) NOT NULL UNIQUE,
    sifre VARCHAR(100) NOT NULL,
    rol VARCHAR(30) NOT NULL,
    aktif_mi BOOLEAN NOT NULL DEFAULT TRUE,
    olusturma_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kategoriler (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kategori_adi VARCHAR(100) NOT NULL,
    aciklama TEXT,
    aktif_mi BOOLEAN NOT NULL DEFAULT TRUE,
    olusturma_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE saklama_kosullari (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kosul_adi VARCHAR(100) NOT NULL,
    kategori_anahtar_kelime VARCHAR(100) NOT NULL,
    onerilen_sicaklik VARCHAR(50) NOT NULL,
    nem_orani VARCHAR(50) NOT NULL,
    saklama_aciklamasi TEXT,
    aktif_mi BOOLEAN NOT NULL DEFAULT TRUE,
    olusturma_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- Urun tablosu: kategori ve saklama kosulu iliskilerini tasir.
-- ============================================================

CREATE TABLE urunler (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kategori_id INTEGER NOT NULL,
    saklama_kosulu_id INTEGER,
    urun_adi VARCHAR(120) NOT NULL,
    barkod VARCHAR(50) NOT NULL UNIQUE,
    birim VARCHAR(30) NOT NULL,
    stok_miktari INTEGER NOT NULL DEFAULT 0,
    kritik_stok_seviyesi INTEGER NOT NULL DEFAULT 0,
    alis_fiyati NUMERIC(10,2) NOT NULL DEFAULT 0,
    satis_fiyati NUMERIC(10,2) NOT NULL DEFAULT 0,
    aciklama TEXT,
    aktif_mi BOOLEAN NOT NULL DEFAULT TRUE,
    olusturma_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_urunler_kategoriler
        FOREIGN KEY (kategori_id) REFERENCES kategoriler(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_urunler_saklama_kosullari
        FOREIGN KEY (saklama_kosulu_id) REFERENCES saklama_kosullari(id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT chk_urunler_stok_miktari
        CHECK (stok_miktari >= 0),
    CONSTRAINT chk_urunler_kritik_stok_seviyesi
        CHECK (kritik_stok_seviyesi >= 0),
    CONSTRAINT chk_urunler_alis_fiyati
        CHECK (alis_fiyati >= 0),
    CONSTRAINT chk_urunler_satis_fiyati
        CHECK (satis_fiyati >= 0)
);

-- ============================================================
-- Stok hareket tablolari: giris ve cikis kayitlari burada tutulur.
-- ============================================================

CREATE TABLE stok_girisler (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    urun_id INTEGER NOT NULL,
    kullanici_id INTEGER NOT NULL,
    miktar INTEGER NOT NULL,
    aciklama TEXT,
    giris_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stok_girisler_urunler
        FOREIGN KEY (urun_id) REFERENCES urunler(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_stok_girisler_kullanicilar
        FOREIGN KEY (kullanici_id) REFERENCES kullanicilar(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_stok_girisler_miktar
        CHECK (miktar > 0)
);

CREATE TABLE stok_cikislar (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    urun_id INTEGER NOT NULL,
    kullanici_id INTEGER NOT NULL,
    miktar INTEGER NOT NULL,
    aciklama TEXT,
    cikis_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stok_cikislar_urunler
        FOREIGN KEY (urun_id) REFERENCES urunler(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_stok_cikislar_kullanicilar
        FOREIGN KEY (kullanici_id) REFERENCES kullanicilar(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_stok_cikislar_miktar
        CHECK (miktar > 0)
);

-- ============================================================
-- Kritik stok ve raporlama tablolari
-- ============================================================

CREATE TABLE kritik_stoklar (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    urun_id INTEGER NOT NULL,
    stok_miktari INTEGER NOT NULL,
    kritik_stok_seviyesi INTEGER NOT NULL,
    kontrol_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_kritik_stoklar_urunler
        FOREIGN KEY (urun_id) REFERENCES urunler(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_kritik_stoklar_stok_miktari
        CHECK (stok_miktari >= 0),
    CONSTRAINT chk_kritik_stoklar_kritik_stok_seviyesi
        CHECK (kritik_stok_seviyesi >= 0)
);

CREATE TABLE raporlar (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kullanici_id INTEGER NOT NULL,
    rapor_turu VARCHAR(50) NOT NULL,
    rapor_basligi VARCHAR(150) NOT NULL,
    rapor_aciklama TEXT,
    olusturma_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_raporlar_kullanicilar
        FOREIGN KEY (kullanici_id) REFERENCES kullanicilar(id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ============================================================
-- AI sorgu gecmisi: saklama kosulu onerilerinin gecmisi tutulur.
-- ============================================================

CREATE TABLE ai_sorgu_gecmisi (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    urun_adi VARCHAR(120) NOT NULL,
    kategori_adi VARCHAR(100) NOT NULL,
    gelen_oneri TEXT NOT NULL,
    kaynak VARCHAR(100) NOT NULL,
    sorgu_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- Ornek veriler: final projesini ilk acilista tanitmak icin kullanilir.
-- Turkce karakter kaynakli kodlama sorunlarini onlemek icin ASCII metin kullanildi.
-- ============================================================

INSERT INTO kullanicilar (ad_soyad, kullanici_adi, sifre, rol)
VALUES ('Sistem Yoneticisi', 'admin', '1234', 'Yonetici');

INSERT INTO kategoriler (kategori_adi, aciklama)
VALUES
    ('Gida', 'Gida urunleri kategorisi'),
    ('Icecek', 'Icecek urunleri kategorisi'),
    ('Temizlik', 'Temizlik urunleri kategorisi'),
    ('Elektronik', 'Elektronik urunler kategorisi'),
    ('Kirtasiye', 'Kirtasiye urunleri kategorisi'),
    ('Soguk Zincir', 'Soguk zincir ile saklanmasi gereken urunler');

INSERT INTO saklama_kosullari
    (kosul_adi, kategori_anahtar_kelime, onerilen_sicaklik, nem_orani, saklama_aciklamasi)
VALUES
    ('Kuru Gida Saklama', 'Gida', '18-24 C', '%40-%60', 'Kuru ve gunes almayan ortamda saklanmalidir.'),
    ('Soguk Zincir Saklama', 'Soguk Zincir', '0-4 C', '%50-%70', 'Soguk zincir bozulmadan buzdolabi kosullarinda saklanmalidir.'),
    ('Temizlik Urunleri Saklama', 'Temizlik', '15-25 C', '%30-%60', 'Kimyasal urunler gidalardan ayri ve kapali alanda saklanmalidir.'),
    ('Elektronik Urun Saklama', 'Elektronik', '10-30 C', '%30-%50', 'Nemden ve dogrudan isidan korunmalidir.'),
    ('Kirtasiye Urunleri Saklama', 'Kirtasiye', '15-25 C', '%35-%60', 'Kuru ve duzenli raf sisteminde saklanmalidir.');

INSERT INTO urunler
    (kategori_id, saklama_kosulu_id, urun_adi, barkod, birim, stok_miktari, kritik_stok_seviyesi, alis_fiyati, satis_fiyati, aciklama)
VALUES
    (
        (SELECT id FROM kategoriler WHERE kategori_adi = 'Soguk Zincir'),
        (SELECT id FROM saklama_kosullari WHERE kosul_adi = 'Soguk Zincir Saklama'),
        'Sut', '869000000001', 'Adet', 50, 10, 18.50, 25.00, 'Soguk zincir urunu'
    ),
    (
        (SELECT id FROM kategoriler WHERE kategori_adi = 'Soguk Zincir'),
        (SELECT id FROM saklama_kosullari WHERE kosul_adi = 'Soguk Zincir Saklama'),
        'Yogurt', '869000000002', 'Adet', 40, 8, 22.00, 30.00, 'Soguk zincir urunu'
    ),
    (
        (SELECT id FROM kategoriler WHERE kategori_adi = 'Kirtasiye'),
        (SELECT id FROM saklama_kosullari WHERE kosul_adi = 'Kirtasiye Urunleri Saklama'),
        'A4 Kagit', '869000000003', 'Paket', 80, 15, 90.00, 125.00, 'Ofis kagidi'
    ),
    (
        (SELECT id FROM kategoriler WHERE kategori_adi = 'Kirtasiye'),
        (SELECT id FROM saklama_kosullari WHERE kosul_adi = 'Kirtasiye Urunleri Saklama'),
        'Kalem', '869000000004', 'Adet', 150, 25, 4.50, 8.00, 'Tukenmez kalem'
    ),
    (
        (SELECT id FROM kategoriler WHERE kategori_adi = 'Temizlik'),
        (SELECT id FROM saklama_kosullari WHERE kosul_adi = 'Temizlik Urunleri Saklama'),
        'Camasir Suyu', '869000000005', 'Adet', 35, 7, 28.00, 42.00, 'Temizlik urunu'
    ),
    (
        (SELECT id FROM kategoriler WHERE kategori_adi = 'Elektronik'),
        (SELECT id FROM saklama_kosullari WHERE kosul_adi = 'Elektronik Urun Saklama'),
        'Telefon Sarj Aleti', '869000000006', 'Adet', 25, 5, 120.00, 190.00, 'Elektronik aksesuar'
    ),
    (
        (SELECT id FROM kategoriler WHERE kategori_adi = 'Icecek'),
        (SELECT id FROM saklama_kosullari WHERE kosul_adi = 'Kuru Gida Saklama'),
        'Su', '869000000007', 'Adet', 200, 30, 3.00, 7.00, 'Sise su'
    ),
    (
        (SELECT id FROM kategoriler WHERE kategori_adi = 'Gida'),
        (SELECT id FROM saklama_kosullari WHERE kosul_adi = 'Kuru Gida Saklama'),
        'Biskuvi', '869000000008', 'Paket', 120, 20, 9.50, 15.00, 'Paketli gida'
    );

INSERT INTO kritik_stoklar (urun_id, stok_miktari, kritik_stok_seviyesi)
SELECT id, stok_miktari, kritik_stok_seviyesi
FROM urunler
WHERE stok_miktari <= kritik_stok_seviyesi;

INSERT INTO raporlar (kullanici_id, rapor_turu, rapor_basligi, rapor_aciklama)
VALUES (
    (SELECT id FROM kullanicilar WHERE kullanici_adi = 'admin'),
    'Genel Stok',
    'Ilk Stok Durum Raporu',
    'Veritabani kurulumundan sonra olusturulan ornek rapor kaydi.'
);

INSERT INTO ai_sorgu_gecmisi (urun_adi, kategori_adi, gelen_oneri, kaynak)
VALUES
    ('Sut', 'Soguk Zincir', '0-4 C araliginda ve soguk zincir bozulmadan saklanmalidir.', 'Ornek Veri'),
    ('Telefon Sarj Aleti', 'Elektronik', 'Nemden uzak, kuru ve oda sicakliginda saklanmalidir.', 'Ornek Veri');
