-- ============================================================
-- StokTakipSistemi PostgreSQL veritabani kurulum dosyasi
-- Bu dosya tabloları, iliskileri, kontrolleri ve ornek verileri olusturur.
-- ============================================================

-- Once iliskili alt tablolar silinir, sonra ana tablolar silinir.
DROP TABLE IF EXISTS ai_sorgu_gecmisi;
DROP TABLE IF EXISTS raporlar;
DROP TABLE IF EXISTS kritik_stoklar;
DROP TABLE IF EXISTS stok_cikislar;
DROP TABLE IF EXISTS stok_girisler;
DROP TABLE IF EXISTS urunler;
DROP TABLE IF EXISTS saklama_kosullari;
DROP TABLE IF EXISTS kategoriler;
DROP TABLE IF EXISTS kullanicilar;

-- ============================================================
-- Ana tablolar: kullanicilar, kategoriler ve saklama kosullari
-- ============================================================

CREATE TABLE kullanicilar (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad_soyad VARCHAR(100) NOT NULL,
    kullanici_adi VARCHAR(50) NOT NULL UNIQUE,
    sifre VARCHAR(100) NOT NULL,
    rol VARCHAR(30) NOT NULL,
    aktif_mi BOOLEAN NOT NULL DEFAULT TRUE,
    olusturma_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kategoriler (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kategori_adi VARCHAR(100) NOT NULL,
    aciklama TEXT,
    aktif_mi BOOLEAN NOT NULL DEFAULT TRUE,
    olusturma_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE saklama_kosullari (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kosul_adi VARCHAR(100) NOT NULL,
    kategori_anahtar_kelime VARCHAR(100) NOT NULL,
    onerilen_sicaklik VARCHAR(50) NOT NULL,
    nem_orani VARCHAR(50) NOT NULL,
    saklama_aciklamasi TEXT,
    aktif_mi BOOLEAN NOT NULL DEFAULT TRUE,
    olusturma_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- Urun tablosu: kategori ve saklama kosulu iliskilerini tasir.
-- ============================================================

CREATE TABLE urunler (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kategori_id INTEGER NOT NULL,
    saklama_kosulu_id INTEGER,
    urun_adi VARCHAR(120) NOT NULL,
    barkod VARCHAR(50) NOT NULL UNIQUE,
    birim VARCHAR(30) NOT NULL,
    stok_miktari INTEGER NOT NULL DEFAULT 0,
    kritik_stok_seviyesi INTEGER NOT NULL DEFAULT 0,
    alis_fiyati NUMERIC(10,2) NOT NULL DEFAULT 0,
    satis_fiyati NUMERIC(10,2) NOT NULL DEFAULT 0,
    aciklama TEXT,
    aktif_mi BOOLEAN NOT NULL DEFAULT TRUE,
    olusturma_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_urunler_kategoriler
        FOREIGN KEY (kategori_id) REFERENCES kategoriler(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_urunler_saklama_kosullari
        FOREIGN KEY (saklama_kosulu_id) REFERENCES saklama_kosullari(id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT chk_urunler_stok_miktari
        CHECK (stok_miktari >= 0),
    CONSTRAINT chk_urunler_kritik_stok_seviyesi
        CHECK (kritik_stok_seviyesi >= 0),
    CONSTRAINT chk_urunler_alis_fiyati
        CHECK (alis_fiyati >= 0),
    CONSTRAINT chk_urunler_satis_fiyati
        CHECK (satis_fiyati >= 0)
);

-- ============================================================
-- Stok hareket tablolari: giris ve cikis kayitlari burada tutulur.
-- ============================================================

CREATE TABLE stok_girisler (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    urun_id INTEGER NOT NULL,
    kullanici_id INTEGER NOT NULL,
    miktar INTEGER NOT NULL,
    aciklama TEXT,
    giris_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stok_girisler_urunler
        FOREIGN KEY (urun_id) REFERENCES urunler(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_stok_girisler_kullanicilar
        FOREIGN KEY (kullanici_id) REFERENCES kullanicilar(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_stok_girisler_miktar
        CHECK (miktar > 0)
);

CREATE TABLE stok_cikislar (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    urun_id INTEGER NOT NULL,
    kullanici_id INTEGER NOT NULL,
    miktar INTEGER NOT NULL,
    aciklama TEXT,
    cikis_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stok_cikislar_urunler
        FOREIGN KEY (urun_id) REFERENCES urunler(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_stok_cikislar_kullanicilar
        FOREIGN KEY (kullanici_id) REFERENCES kullanicilar(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_stok_cikislar_miktar
        CHECK (miktar > 0)
);

-- ============================================================
-- Kritik stok ve raporlama tablolari
-- ============================================================

CREATE TABLE kritik_stoklar (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    urun_id INTEGER NOT NULL,
    stok_miktari INTEGER NOT NULL,
    kritik_stok_seviyesi INTEGER NOT NULL,
    kontrol_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_kritik_stoklar_urunler
        FOREIGN KEY (urun_id) REFERENCES urunler(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_kritik_stoklar_stok_miktari
        CHECK (stok_miktari >= 0),
    CONSTRAINT chk_kritik_stoklar_kritik_stok_seviyesi
        CHECK (kritik_stok_seviyesi >= 0)
);

CREATE TABLE raporlar (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kullanici_id INTEGER NOT NULL,
    rapor_turu VARCHAR(50) NOT NULL,
    rapor_basligi VARCHAR(150) NOT NULL,
    rapor_aciklama TEXT,
    olusturma_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_raporlar_kullanicilar
        FOREIGN KEY (kullanici_id) REFERENCES kullanicilar(id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ============================================================
-- AI sorgu gecmisi: saklama kosulu onerilerinin gecmisi tutulur.
-- ============================================================

CREATE TABLE ai_sorgu_gecmisi (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    urun_adi VARCHAR(120) NOT NULL,
    kategori_adi VARCHAR(100) NOT NULL,
    gelen_oneri TEXT NOT NULL,
    kaynak VARCHAR(100) NOT NULL,
    sorgu_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- Ornek veriler: final projesini ilk acilista tanitmak icin kullanilir.
-- ============================================================

INSERT INTO kullanicilar (ad_soyad, kullanici_adi, sifre, rol)
VALUES ('Sistem Yöneticisi', 'admin', '1234', 'Yonetici');

INSERT INTO kategoriler (kategori_adi, aciklama)
VALUES
    ('Gıda', 'Gıda ürünleri kategorisi'),
    ('İçecek', 'İçecek ürünleri kategorisi'),
    ('Temizlik', 'Temizlik ürünleri kategorisi'),
    ('Elektronik', 'Elektronik ürünler kategorisi'),
    ('Kırtasiye', 'Kırtasiye ürünleri kategorisi'),
    ('Soğuk Zincir', 'Soğuk zincir ile saklanması gereken ürünler');

INSERT INTO saklama_kosullari
    (kosul_adi, kategori_anahtar_kelime, onerilen_sicaklik, nem_orani, saklama_aciklamasi)
VALUES
    ('Kuru Gıda Saklama', 'Gıda', '18-24 °C', '%40-%60', 'Kuru ve güneş almayan ortamda saklanmalıdır.'),
    ('Soğuk Zincir Saklama', 'Soğuk Zincir', '0-4 °C', '%50-%70', 'Soğuk zincir bozulmadan buzdolabı koşullarında saklanmalıdır.'),
    ('Temizlik Ürünleri Saklama', 'Temizlik', '15-25 °C', '%30-%60', 'Kimyasal ürünler gıdalardan ayrı ve kapalı alanda saklanmalıdır.'),
    ('Elektronik Ürün Saklama', 'Elektronik', '10-30 °C', '%30-%50', 'Nemden ve doğrudan ısıdan korunmalıdır.'),
    ('Kırtasiye Ürünleri Saklama', 'Kırtasiye', '15-25 °C', '%35-%60', 'Kuru ve düzenli raf sisteminde saklanmalıdır.');

INSERT INTO urunler
    (kategori_id, saklama_kosulu_id, urun_adi, barkod, birim, stok_miktari, kritik_stok_seviyesi, alis_fiyati, satis_fiyati, aciklama)
VALUES
    (
        (SELECT id FROM kategoriler WHERE kategori_adi = 'Soğuk Zincir'),
        (SELECT id FROM saklama_kosullari WHERE kosul_adi = 'Soğuk Zincir Saklama'),
        'Süt', '869000000001', 'Adet', 50, 10, 18.50, 25.00, 'Soğuk zincir ürünü'
    ),
    (
        (SELECT id FROM kategoriler WHERE kategori_adi = 'Soğuk Zincir'),
        (SELECT id FROM saklama_kosullari WHERE kosul_adi = 'Soğuk Zincir Saklama'),
        'Yoğurt', '869000000002', 'Adet', 40, 8, 22.00, 30.00, 'Soğuk zincir ürünü'
    ),
    (
        (SELECT id FROM kategoriler WHERE kategori_adi = 'Kırtasiye'),
        (SELECT id FROM saklama_kosullari WHERE kosul_adi = 'Kırtasiye Ürünleri Saklama'),
        'A4 Kağıt', '869000000003', 'Paket', 80, 15, 90.00, 125.00, 'Ofis kağıdı'
    ),
    (
        (SELECT id FROM kategoriler WHERE kategori_adi = 'Kırtasiye'),
        (SELECT id FROM saklama_kosullari WHERE kosul_adi = 'Kırtasiye Ürünleri Saklama'),
        'Kalem', '869000000004', 'Adet', 150, 25, 4.50, 8.00, 'Tükenmez kalem'
    ),
    (
        (SELECT id FROM kategoriler WHERE kategori_adi = 'Temizlik'),
        (SELECT id FROM saklama_kosullari WHERE kosul_adi = 'Temizlik Ürünleri Saklama'),
        'Çamaşır Suyu', '869000000005', 'Adet', 35, 7, 28.00, 42.00, 'Temizlik ürünü'
    ),
    (
        (SELECT id FROM kategoriler WHERE kategori_adi = 'Elektronik'),
        (SELECT id FROM saklama_kosullari WHERE kosul_adi = 'Elektronik Ürün Saklama'),
        'Telefon Şarj Aleti', '869000000006', 'Adet', 25, 5, 120.00, 190.00, 'Elektronik aksesuar'
    ),
    (
        (SELECT id FROM kategoriler WHERE kategori_adi = 'İçecek'),
        (SELECT id FROM saklama_kosullari WHERE kosul_adi = 'Kuru Gıda Saklama'),
        'Su', '869000000007', 'Adet', 200, 30, 3.00, 7.00, 'Şişe su'
    ),
    (
        (SELECT id FROM kategoriler WHERE kategori_adi = 'Gıda'),
        (SELECT id FROM saklama_kosullari WHERE kosul_adi = 'Kuru Gıda Saklama'),
        'Bisküvi', '869000000008', 'Paket', 120, 20, 9.50, 15.00, 'Paketli gıda'
    );

INSERT INTO kritik_stoklar (urun_id, stok_miktari, kritik_stok_seviyesi)
SELECT id, stok_miktari, kritik_stok_seviyesi
FROM urunler
WHERE stok_miktari <= kritik_stok_seviyesi;

INSERT INTO raporlar (kullanici_id, rapor_turu, rapor_basligi, rapor_aciklama)
VALUES (
    (SELECT id FROM kullanicilar WHERE kullanici_adi = 'admin'),
    'Genel Stok',
    'İlk Stok Durum Raporu',
    'Veritabanı kurulumundan sonra oluşturulan örnek rapor kaydı.'
);

INSERT INTO ai_sorgu_gecmisi (urun_adi, kategori_adi, gelen_oneri, kaynak)
VALUES
    ('Süt', 'Soğuk Zincir', '0-4 °C aralığında ve soğuk zincir bozulmadan saklanmalıdır.', 'Örnek Veri'),
    ('Telefon Şarj Aleti', 'Elektronik', 'Nemden uzak, kuru ve oda sıcaklığında saklanmalıdır.', 'Örnek Veri');
